[project]
name = "pro-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "uguryildirim24", email = "ugur_yildirim24@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mcp>=2.2.0",
    "textual>=8.2.8",
]

[project.scripts]
pro-mcp = "pro_mcp:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
